server:
  port: 9000

spring:
  application:
    name: piralfeed
    version: "@project.version@"
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/piralfeed
    username: root
    password: piralfeed
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 900000
      connection-timeout: 10000
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 10
  cache:
    jcache:
      config: classpath:ehcache.xml
  liquibase:
    change-log: classpath:liquibase/master.xml
    user: root
    password: piralfeed

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  tags:
    environment: ${spring.config.activate.on-profile}

springdoc:
  api-docs:
    enabled: true

logging:
  level:
    io.piral.feedservice: DEBUG

application:
  file-url: http://localhost:${server.port}/api/v1/pilets/files/%s/%s/%s/index.js
  security:
    basic:
      username: piralfeed_piletpublish_user
      password: piralfeed_piletpublish_password